using FetchMeFoss.Concretes;

namespace FetchMeFoss.Models
{
    // todo 3;
    public class FossObjectConsts
    {
        public static Dictionary<string, Type> FossItemType = new Dictionary<string, Type>
        {
            {".netframework", typeof(DotNetFramework) },
            {".netruntime", typeof(DotNetRuntime) },
            {"7z", typeof(SevenZip) },
            {"7zip", typeof(SevenZip) },
            {"ableton", typeof(AbletonLiveLite) },
            {"ahk", typeof(AutoHotkey) },
            {"anki", typeof(Anki) },
            {"audacious", typeof(Audacious) },
            {"audacity", typeof(Audacity) },
            {"authy", typeof(Authy) },
            {"autohotkey", typeof(AutoHotkey) },
            {"bulkrenameutility", typeof(BulkRenameUtility) },
            {"calibre", typeof(Calibre) },
            {"chrome", typeof(GoogleChrome) },
            {"chromium", typeof(Chromium) },
            {"discord", typeof(Discord) },
            {"dotnetframework", typeof(DotNetFramework) },
            {"dotnetruntime", typeof(DotNetRuntime) },
            {"eaorigin", typeof(EaOrigin) },
            {"eclipse", typeof(Eclipse) },
            {"epicgames", typeof(EpicGames) },
            {"ffmpeg", typeof(Ffmpeg) },
            {"filezilla", typeof(Filezilla) },
            {"firefox", typeof(Firefox) },
            {"freefilesync", typeof(FreeFileSync) },
            {"gimp", typeof(Gimp) },
            {"git", typeof(Git) },
            {"gitforwindows", typeof(Git) },
            {"gnucash", typeof(Gnucash) },
            {"googlechrome", typeof(GoogleChrome) },
            {"greenshot", typeof(Greenshot) },
            {"handbrake", typeof(Handbrake) },
            {"huiontablet", typeof(HuionTabletDriver) },
            {"huiontabletdriver", typeof(HuionTabletDriver) },
            {"imageglass", typeof(Imageglass) },
            {"intellij", typeof(Intellij) },
            {"intellijidea", typeof(Intellij) },
            {"java", typeof(Java) },
            {"kate", typeof(Kate) },
            {"kdenlive", typeof(Kdenlive) },
            {"keepass", typeof(Keepass) },
            {"keepassxc", typeof(KeepassXC) },
            {"krita", typeof(Krita) },
            {"libreoffice", typeof(LibreOffice) },
            {"logitechmousedriver", typeof(LogitechMouseDriver) },
            {"massimagecompressor", typeof(MassImageCompressor) },
            {"microsoftoffice", typeof(MicrosoftOffice) },
            {"microsoftteams", typeof(MicrosoftTeams) },
            {"mp3tag", typeof(Mp3Tag) },
            {"msoffice", typeof(MicrosoftOffice) },
            {"n++", typeof(NotepadPlusPlus) },
            {"nativeinstruments", typeof(NativeInstruments) },
            {"node", typeof(NodeJs) },
            {"nodejs", typeof(NodeJs) },
            {"notepad++", typeof(NotepadPlusPlus) },
            {"notepadplusplus", typeof(NotepadPlusPlus) },
            {"nvidia", typeof(NvidiaDrivers) },
            {"nvidiadrivers", typeof(NvidiaDrivers) },
            {"obs", typeof(OpenBroadcastSoftware) },
            {"office", typeof(MicrosoftOffice) },
            {"office365", typeof(MicrosoftOffice) },
            {"okular", typeof(Okular) },
            {"openbroadcastsoftware", typeof(OpenBroadcastSoftware) },
            {"openhardwaremonitor", typeof(OpenHardwareMonitor) },
            {"openshot", typeof(OpenShot) },
            {"opera", typeof(Opera) },
            {"oraclevirtualbox", typeof(VirtualBox) },
            {"origin", typeof(EaOrigin) },
            {"pdfsam", typeof(Pdfsam) },
            {"python", typeof(Python) },
            {"rufus", typeof(Rufus) },
            {"scribus", typeof(Scribus) },
            {"sevenzip", typeof(SevenZip) },
            {"skype", typeof(Skype) },
            {"steam", typeof(Steam) },
            {"sumatra", typeof(Sumatra) },
            {"sumatrapdf", typeof(Sumatra) },
            {"teams", typeof(MicrosoftTeams) },
            {"thunderbird", typeof(Thunderbird) },
            {"tor", typeof(Tor) },
            {"twitch", typeof(Twitch) },
            {"ubisof", typeof(UbisoftConnect) },
            {"ubisoftconnect", typeof(UbisoftConnect) },
            {"virtualbox", typeof(VirtualBox) },
            {"visualstudio", typeof(VisualStudio) },
            {"visualstudiocode", typeof(VsCode) },
            {"visualstudiocommunity", typeof(VisualStudio) },
            {"vlc", typeof(Vlc) },
            {"vnc", typeof(Vnc) },
            {"vncviewer", typeof(Vnc) },
            {"vscode", typeof(VsCode) },
            {"windirstat", typeof(WinDirStat) },
            {"winrar", typeof(WinRar) },
            {"winscp", typeof(WinScp) },
            {"zoom", typeof(Zoom) },

        };
    }
}
