using FetchMeFoss.Concretes;

namespace FetchMeFoss.Models
{
    // todo 3;
    public class FossDataConstants
    {
        // todo 1; implmement all these
        public static Dictionary<string, Type> FossItemType = new Dictionary<string, Type>
        {
            //{"7zip", typeof(SevenZip) },
            //{"7z", typeof(SevenZip) },
           // {"sevenzip", typeof(SevenZip) },
           // {"ableton", typeof(Ableton) },
           // {"anki", typeof(Anki) },
           // {"audacious", typeof(Audacious) },
           // {"autohotkey", typeof(AutoHotkey) },
           //{"audacity", typeof(Audacity) },
           // {"authy", typeof(Authy) },
           // {"bulkrenameutility", typeof(BulkRenameUtility) },
           // {"dotnet", typeof(DotNetRuntime) },
           // {".net", typeof(DotNetRuntime) },
           // {".netframework", typeof(DotNetFramework) },
           // {"dotnetframework", typeof(DotNetFramework) },
           // {"calibre", typeof(Calibre) },
           // {"chrome", typeof(GoogleChrome) },
           // {"discord", typeof(Discord) },
           // {"googlechrome", typeof(GoogleChrome) },
           // {"chromium", typeof(Chromium) },
           // {"eaorigin", typeof(EaOrigin) },
           // {"origin", typeof(EaOrigin) },
           // {"eclipse", typeof(Eclipse) },
           // {"epicgames", typeof(EpicGames) },
           // {"ffmpeg", typeof(Ffmpeg) },
           // {"filezilla", typeof(Filezilla) },
           // {"firefox", typeof(Firefox) },
           // {"freefilesync", typeof(FreeFileSync) },
           // {"gimp", typeof(Gimp) },
            {"git", typeof(Git) },
           // {"gitforwindows", typeof(Git) },
           // {"gnucash", typeof(Gnucash) },
           // {"greenshot", typeof(Greenshot) },
           // {"handbrake", typeof(Handbrake) },
           // {"huiontabletdriver", typeof(HuionTabletDriver) },
           // {"imageglass", typeof(Imageglass) },
           // {"intellij", typeof(Intellij) },
           // {"java", typeof(Java) },
           // {"kate", typeof(Kate) },
           // {"kdenlive", typeof(Kdenlive) },
           // {"keepass", typeof(Keepass) },
           // {"keepassxc", typeof(KeepassXC) },
           {"krita", typeof(Krita) },
           // {"libreoffice", typeof(LibreOffice) },
           // {"logitechmousedriver", typeof(LogitechMouseDriver) },
           // {"massimagecompressor", typeof(MassImageCompressor) },
           // {"microsoftteams", typeof(MicrosoftTeams) },
           // {"microsoftoffice", typeof(MicrosoftOffice) },
           // {"mp3tag", typeof(Mp3Tag) },
           // {"nativeinstruments", typeof(NativeInstruments) },
           // {"nodejs", typeof(NodeJs) },
           // {"node", typeof(NodeJs) },
           // {"nvidiadrivers", typeof(NvidiaDrivers) },
           // {"nvidia", typeof(NvidiaDrivers) },
           // {"n++", typeof(NotepadPlusPlus) },
           // {"notepadplusplus", typeof(NotepadPlusPlus) },
           // {"notepad++", typeof(NotepadPlusPlus) },
           // {"okular", typeof(Okular) },
           // {"openhardwaremonitor", typeof(OpenHardwareMonitor) },
           // {"openshot", typeof(OpenShot) },
           // {"obs", typeof(OpenBroadcastSoftware) },
           // {"openbroadcastsoftware", typeof(OpenBroadcastSoftware) },
           // {"opera", typeof(Opera) },
           // {"pdfsam", typeof(Pdfsam) },
           // {"python", typeof(Python) },
           // {"rufus", typeof(Rufus) },
           // {"skype", typeof(Skype) },
           // {"scribus", typeof(Scribus) },
           // {"steam", typeof(Steam) },
           // {"sumatra", typeof(Sumatra) },
           // {"tor", typeof(Tor) },
           // {"thunderbird", typeof(Thunderbird) },
           // {"twitch", typeof(Twitch) },
           // {"ubisoftconnect", typeof(UbisoftConnect) },
           // {"ubisof", typeof(UbisoftConnect) },
           // {"virtualbox", typeof(VirtualBox) },
           // {"visualstudio", typeof(VisualStudio) },
           // {"vlc", typeof(Vlc) },
           // {"vnc", typeof(Vnc) },
           // {"vscode", typeof(VsCode) },
           // {"visualstudiocode", typeof(VsCode) },
           // {"windirstat", typeof(WinDirStat) },
           // {"winrar", typeof(WinRar) },
           // {"winscp", typeof(WinScp) },
           // {"zoom", typeof(Zoom) },
        };
    }
}
